source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", "2.6.1"
  gem "cloudcannon-jekyll-bookshop", "2.6.1"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "jekyll-pagebreak", "~> 0.9.1"
  gem 'jekyll_picture_tag', '~> 2.0'
  gem 'jekyll-minifier'
end
