source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.4.0"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "jekyll-pagebreak", "~> 0.9.1"
  gem 'jekyll_picture_tag', '~> 2.0'
  gem 'jekyll-i18n-tags', :path => "./_plugins/jekyll-i18n-tags"
end
